### ISSUE TITLE
Error: Cannot find module in Extensions

### ISSUE THREAD

**Issue by JoaquinDecima** [NodeBB/NodeBB#11203]
### NodeBB version

v2.8.2

### NodeBB git hash

050e43f8b4fad2f37603c38525373e3e17b28684

### NodeJS version

v18.12.1

### Installed NodeBB plugins

* @nodebb/nodebb-plugin-reactions@1.0.2 (installed, enabled)
* nodebb-plugin-2factor@5.1.2 (installed, disabled)
* nodebb-plugin-adsense@2.0.0 (installed, enabled)
* nodebb-plugin-category-join-group@4.0.0 (installed, enabled)
* nodebb-plugin-composer-default@9.2.4 (installed, enabled)
* nodebb-plugin-customize@2.0.5 (installed, enabled)
* nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
* nodebb-plugin-embed@3.0.19 (installed, enabled)
* nodebb-plugin-emoji@4.0.6 (installed, enabled)
* nodebb-plugin-emoji-one@3.0.0 (installed, enabled)
* nodebb-plugin-extended-markdown@1.6.0 (installed, enabled)
* nodebb-plugin-html5videoplayer@0.2.5 (installed, enabled)
* nodebb-plugin-imgbed@0.2.1 (installed, enabled)
* nodebb-plugin-markdown@10.1.1 (installed, enabled)
* nodebb-plugin-medals@0.6.5 (installed, enabled)
* nodebb-plugin-mentions@3.0.12 (installed, enabled)
* nodebb-plugin-ns-spoiler@8.0.0 (installed, enabled)
* nodebb-plugin-poll@2.0.7 (installed, enabled)
* nodebb-plugin-question-and-answer@0.12.29 (installed, enabled)
* nodebb-plugin-recent-cards-niuniu@2.0.6 (installed, enabled)
* nodebb-plugin-seo@1.0.0 (installed, enabled)
* nodebb-plugin-share-bar@1.0.2 (installed, enabled)
* nodebb-plugin-spam-be-gone@1.0.2 (installed, enabled)
* nodebb-plugin-tenor-gif@3.0.0 (installed, enabled)
* nodebb-plugin-user-level@0.4.3 (installed, enabled)
* nodebb-plugin-vs-twitch-monitor@3.1.2 (installed, enabled)
* nodebb-rewards-essentials@0.2.1 (installed, disabled)
* nodebb-theme-persona@12.1.12 (installed, enabled)
* nodebb-widget-essentials@6.0.1 (installed, enabled)

### Database type

MongoDB

### Database version

v4.0.10

### Exact steps to cause this issue

1. Go to Admin Panel
2. Go to Extensions -> Any extension

### What you expected

Extensions can be configured and work correctly

### What happened instead

Some appear with a blank screen and others do not allow changing settings or saving. When clicking on the buttons, it does not save

The following appears in the Google Chrome terminal (With any Extension):

```javascript
admin.min.js?v=mhqmb9k35t4:1 error loading admin/plugins/customize
Error: Cannot find module './plugins/customize'
    at https://community.vasak.net.ar/assets/admin.min.js?v=mhqmb9k35t4:1:20243
    at async g (https://community.vasak.net.ar/assets/admin.min.js?v=mhqmb9k35t4:1:33014)
    at async Promise.all (index 0)
    at async app.require (https://community.vasak.net.ar/assets/admin.min.js?v=mhqmb9k35t4:2:54)
    at async https://community.vasak.net.ar/assets/admin.min.js?v=mhqmb9k35t4:1:26998
```

**Comment by pitaj** [comment]
Customize plugin is currently broken on NodeBB v2. I'm working on it.

**Comment by JoaquinDecima** [comment]
Sure @pitaj , but the problem is with all plugins, not just this one.

**Comment by pitaj** [comment]
Okay so first of all, NodeBB doesn't have extensions, but Plugins. Secondly, did you recently upgrade or is this a fresh install? If you did upgrade, what steps did you take and did you encounter any errors? Third, have you tried rebuilding and restarting NodeBB? If the button in the ACP has no effect, try executing the following from the command line:

    ./nodebb stop
    ./nodebb build
    ./nodebb start

**Comment by JoaquinDecima** [comment]
Sorry, ok I explain better.

The installation is clean (currently upgrade to 2.8.3) according to the guide https://docs.nodebb.org/configuring/upgrade/ and without any problems.

I was able to notice that there are some plugins that do not generate this error, however the rest do generate it without following a pattern. However, I saw that version 2.8.3 brings a fix for the plugins, so it could be that.

**Comment by JoaquinDecima** [comment]
Update,

Being in the new version, activate the emoji plugin again. I went back to build and restarted the service, but it gives the exact same error.

**Comment by julianlam** [comment]
@JoaquinDecima Not all plugins are compatible with NodeBB v2.x, let us know which ones are not. We cannot guarantee compatibility with all plugins (nor can we fix the ones we don't control), fyi.

**Comment by vicnguyenqt** [comment]
> @JoaquinDecima Not all plugins are compatible with NodeBB v2.x, let us know which ones are not. We cannot guarantee compatibility with all plugins (nor can we fix the ones we don't control), fyi.

After upgrading to v2.8, went through all admin pages, got warning from Chrome dev tools

At assets/admin.min.js

Cannot find module './settings/user'
Cannot find module './plugins/gravatar'
Cannot find module './development/logger'
Cannot find module './advanced/hooks'
Cannot find module './advanced/database'
Cannot find module './plugins/s3-uploads'
Cannot find module './settings/reputation'
Cannot find module './settings/guest'
Cannot find module './settings/tags'
Cannot find module './settings/post'
Cannot find module './settings/uploads'
Cannot find module './settings/languages'
Cannot find module './settings/chat'
Cannot find module './settings/pagination'
Cannot find module './settings/advanced'
Cannot find module './settings/web-crawler'
Cannot find module './dashboard/searches'

**Comment by julianlam** [comment]
That's fine. The error is thrown because it tries to load the file but if that page does not have any client-side js, then the request will fail. The app will still continue to work fine.
