### ISSUE TITLE
[PostCSS] Styles rebuild error 

### ISSUE THREAD

**Issue by youhosi** [NodeBB/NodeBB#8882]
- **NodeBB version:** 1.15.1
- **NodeBB git hash:** 85aaededaeced4b155744330a712a7c72e2c6e4f
- **Installed NodeBB Plugins:** 

```
Active plugins:
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-custom-pages (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-android (installed, disabled)
	* nodebb-plugin-emoji-apple (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, disabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-oxide (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)
```

- **Database type:** mongo
- **Database version:** 5.0.5
- **Exact steps to cause this issue:**

Hello, when I try to rebuild the forum `./nodebb build | ./nodebb build styles`, I get an error called `postcss`

- **What happened instead:**

```
xxx@umod/var/www/$ ./nodebb build --series styles

2020-11-14T09:34:25.685Z [8000,8001,8002/21114] - info: [build] Building in series mode
2020-11-14T09:34:25.687Z [8000,8001,8002/21114] - info: [build]         client side styles  build started
TypeError: node.addToError is not a function
    at LazyResult.handleError (/var/www/node_modules/postcss/lib/lazy-result.js:290:22)
    at LazyResult.visitTick (/var/www/node_modules/postcss/lib/lazy-result.js:435:20)
    at LazyResult.runAsync (/var/www/node_modules/postcss/lib/lazy-result.js:345:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-11-14T09:34:33.630Z [8000,8001,8002/21114] - error: [build]         client side styles  build failed
2020-11-14T09:34:33.631Z [8000,8001,8002/21114] - error: [build] Encountered error during build step
TypeError: node.toProxy is not a function
    at LazyResult.visitTick (/var/www/node_modules/postcss/lib/lazy-result.js:433:29)
    at LazyResult.runAsync (/var/www/node_modules/postcss/lib/lazy-result.js:345:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-11-14T09:34:33.631Z [8000,8001,8002/21114] - error: TypeError: node.toProxy is not a function
    at LazyResult.visitTick (/var/www/node_modules/postcss/lib/lazy-result.js:433:29)
    at LazyResult.runAsync (/var/www/node_modules/postcss/lib/lazy-result.js:345:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by barisusakli** [comment]
Can you post the versions of postcss and autoprefixer?
I got this error too but was resolved after running npm i

**Comment by youhosi** [comment]
```
  "autoprefixer": "^10.0.0",  
  "postcss": "8.1.7",
```

I updated all npm packages with new ones (also remove node_modules) and unfortunately, same problem

**Comment by barisusakli** [comment]
Can you post the output of these 
`npm ls autoprefixer` 
`npm ls postcss`

Also try installing an older postcss and try building again
`npm i postcss@8.0.6`

**Comment by youhosi** [comment]
@barisusakli thanks, now its working! ❤️

**Comment by barisusakli** [comment]
So it's working on "postcss": "8.0.6" and broken on "postcss": "8.1.7" ?

**Comment by youhosi** [comment]
After installing `"postcss": "8.0.6"` nodebb started building the forum normally
