### PR TITLE
Misc fixes and improvements

### LINKED ISSUE #6142: CLI setup does not work in 1.7.1
- **NodeBB version: 1.7.1 (github released tarball)** 
- **Database type:** mongo

On Cloudron, we do the initial setup using `/app/code/app --setup "${setup}"  --series`. Trying to debug the issue, it appears there is a spurious `prestart.loadConfig` introduced by https://github.com/NodeBB/NodeBB/pull/6058 at https://github.com/NodeBB/NodeBB/blob/master/src/cli/setup.js#L22. Not sure how that can work since prestart.loadConfig does not take a callback - https://github.com/NodeBB/NodeBB/blob/master/src/prestart.js#L27

### PR DESCRIPTION
**Pull request by pitaj**
- Better upgrade template
- Enable using the `./nodebb setup` command for auto-setup with a JSON argument
- Change CLI so package-install and dependency install are separate steps
- Fix #6142
- Prevent compiling templates multiple times
  Hopefully fixes race case issue "templateFunction is not a function"

### CODE REVIEW

File: src/upgrades/TEMPLATE [hunk 1]
```diff
@@ -6,7 +6,8 @@ var async = require('async');
 var winston = require('winston');
 
 module.exports = {
-	name: 'User_friendly_upgrade_script_name',
+	name: 'User friendly upgrade script name',
```
Comment (julianlam) [inline src/upgrades/TEMPLATE]: This is underscored so you can double-click to select the whole text

**Comment by julianlam** [comment]
Otherwise LGTM

File: src/upgrades/TEMPLATE (hunk 1 above)
Comment (pitaj) [reply src/upgrades/TEMPLATE]: Drat!
