### ISSUE TITLE
Unable to complete user registration

### ISSUE THREAD

**Issue by MaxWaldorf** [NodeBB/NodeBB#10875]
### NodeBB version

v2.5.1

### NodeBB git hash

2bf475299d0fdffce154979862ddba99cb56b0b5

### NodeJS version

using official nodebb container

### Installed NodeBB plugins

Active plugins:
        * nodebb-plugin-2factor@5.0.2 (installed, disabled)
        * nodebb-plugin-archiver@5.0.2 (installed, enabled)
        * nodebb-plugin-composer-default@9.1.0 (installed, enabled)
        * nodebb-plugin-dbsearch@5.1.5 (installed, enabled)
        * nodebb-plugin-desktop-notifications@0.3.3 (installed, enabled)
        * nodebb-plugin-emoji@4.0.4 (installed, enabled)
        * nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
        * nodebb-plugin-extended-markdown@1.6.0 (installed, enabled)
        * nodebb-plugin-feed@2.0.3 (installed, enabled)
        * nodebb-plugin-google-analytics@0.6.3 (installed, enabled)
        * nodebb-plugin-gravatar@2.3.0 (installed, enabled)
        * nodebb-plugin-hashtags@2.1.5 (installed, enabled)
        * nodebb-plugin-imgur@2.0.5 (installed, enabled)
        * nodebb-plugin-markdown@10.1.0 (installed, enabled)
        * nodebb-plugin-mentions@3.0.11 (installed, enabled)
        * nodebb-plugin-night-mode@1.0.7 (installed, enabled)
        * nodebb-plugin-ns-embed@6.0.0 (installed, enabled)
        * nodebb-plugin-openidconnect@0.0.2 (installed, enabled)
        * nodebb-plugin-poll@2.0.6 (installed, enabled)
        * nodebb-plugin-question-and-answer@0.12.25 (installed, enabled)
        * nodebb-plugin-recent-cards@2.0.22 (installed, enabled)
        * nodebb-plugin-soundpack-default@2.0.2 (installed, enabled)
        * nodebb-plugin-spam-be-gone@1.0.0 (installed, enabled)
        * nodebb-plugin-tenor-gif@2.2.0 (installed, enabled)
        * nodebb-rewards-essentials@0.2.1 (installed, enabled)
        * nodebb-theme-lavender@6.0.0 (installed, disabled)
        * nodebb-theme-persona@12.1.1 (installed, enabled)
        * nodebb-theme-slick@2.0.2 (installed, disabled)
        * nodebb-theme-vanilla@12.1.18 (installed, disabled)
        * nodebb-widget-essentials@6.0.0 (installed, enabled)

### Database type

MongoDB

### Database version

v5.0.11

### Exact steps to cause this issue

When user try to register, after entering the first password field, they get:
"t is not a function"

![Screenshot 2022-09-04 at 14 33 42](https://user-images.githubusercontent.com/15877853/188314082-a1901a6f-60fc-48cc-81ee-9ace2bf2fd48.png)

### What you expected

Users cannot complete a full registration...

**Comment by julianlam** [comment]
Upgraded to v2 recently?

Might be an incompatible plugin. Try temporarily disabling any custom plugins and see if the issue persists.

**Comment by MaxWaldorf** [comment]
No I switched to v2 a while ago...
Registrations stoped 2 days ago when I upgraded to v2.5.0 container...

I removed all extensions and still the same...

Let me know what I can do more...

**Comment by barisusakli** [comment]
fix in 2.5.2

**Comment by MaxWaldorf** [comment]
confirmed fixed!

Cheers
