### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by bubbleatgit** [NodeBB/NodeBB#3649]
https://github.com/NodeBB/NodeBB/issues/2556
when i update nodebb to v8.2 ,i got the same problem,but i use redis

**Comment by bubbleatgit** [comment]
```
22/9 18:07 [2251] - error: TypeError: undefined is not a function
    at Redis.onmessage (/data/wwwroot/bbs.gitlab.cc/node_modules/socket.io-redis/index.js:92:26)
    at RedisClient.emit (events.js:118:17)
    at RedisClient.return_reply (/data/wwwroot/bbs.gitlab.cc/node_modules/redis/index.js:624:22)
    at RedisClient.<anonymous> (/data/wwwroot/bbs.gitlab.cc/node_modules/redis/index.js:284:18)
    at process._tickDomainCallback (node.js:381:11)
TypeError: undefined is not a function
    at Redis.onmessage (/data/wwwroot/bbs.gitlab.cc/node_modules/socket.io-redis/index.js:92:26)
    at RedisClient.emit (events.js:118:17)
    at RedisClient.return_reply (/data/wwwroot/bbs.gitlab.cc/node_modules/redis/index.js:624:22)
    at RedisClient.<anonymous> (/data/wwwroot/bbs.gitlab.cc/node_modules/redis/index.js:284:18)
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by barisusakli** [comment]
Try removing node_modules and running npm i again like in #2556, if that doesn't work post the versions of all related modules, ie redis socket.io socket.io-redis nodebb git hash etc.

**Comment by bubbleatgit** [comment]
@barisusakli i reinstalled nodebb,this issue got fix. thanks
