### ISSUE TITLE
Can't "./nodebb upgrade" after updating to v0.7.3

### ISSUE THREAD

**Issue by mrgame64** [NodeBB/NodeBB#3451]
After performing the update via `git fetch & git reset --hard origin/v0.7.x`, running the `./nodebb upgrade` command gives the following output:

```javascript
1. Bringing base dependencies up to date
module.js:338
    throw err;
          ^
Error: Cannot find module '/root/nodebb/node_modules/npm/lib/build.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperty.get (/root/nodebb/node_modules/npm/lib/npm.js:195:15)
    at /root/nodebb/node_modules/npm/lib/install.js:1163:17
    at asyncMap (/root/nodebb/node_modules/npm/node_modules/slide/lib/async-map.js:27:18)
    at andBuildResolvedTree (/root/nodebb/node_modules/npm/lib/install.js:761:9)
    at /root/nodebb/node_modules/npm/lib/install.js:715:9
    at asyncMap (/root/nodebb/node_modules/npm/node_modules/slide/lib/async-map.js:27:18)
```

And yes, I've stopped NodeBB before starting the update.

**Comment by julianlam** [comment]
Hey there @mrgame64... interesting error. Can you run `npm rebuild` and then `./nodebb upgrade` again?

**Comment by mrgame64** [comment]
Sure, just to tell you, after running `./nodebb upgrade` for a second time without `npm rebuild`, I get this:

```javascript
1. Bringing base dependencies up to date
2. Updating NodeBB data store schema
module.js:338
    throw err;
          ^
Error: Cannot find module 'nconf'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/nodebb/app.js:23:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

Error: undefined
```

**Comment by mrgame64** [comment]
Running npm rebuild gave me this:

```javascript
> heapdump@0.3.7 install /root/nodebb/node_modules/heapdump
> node-gyp rebuild

make: Entering directory `/root/nodebb/node_modules/heapdump/build'
make: *** No rule to make target `Release/obj.target/addon/src/heapdump.o', needed by `Release/obj.target/addon.node'. Stop.
make: Leaving directory `/root/nodebb/node_modules/heapdump/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.10.23-xxxx-std-ipv6-64-vps
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/nodebb/node_modules/heapdump
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

npm ERR! Linux 3.10.23-xxxx-std-ipv6-64-vps
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "rebuild"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/nodebb/npm-debug.log
```

And the last lines of npm-debug.log are: 
```
977 silly linkStuff heapdump@0.3.7 has /root/nodebb/node_modules as its parent node_modules
978 verbose linkBins heapdump@0.3.7
979 verbose linkMans heapdump@0.3.7
980 verbose rebuildBundles heapdump@0.3.7
981 info install heapdump@0.3.7
982 verbose unsafe-perm in lifecycle false
983 info heapdump@0.3.7 Failed to exec install script
984 verbose stack Error: heapdump@0.3.7 install: `node-gyp rebuild`
984 verbose stack Exit status 1
984 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
984 verbose stack     at EventEmitter.emit (events.js:110:17)
984 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
984 verbose stack     at ChildProcess.emit (events.js:110:17)
984 verbose stack     at maybeClose (child_process.js:1015:16)
984 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
985 verbose pkgid heapdump@0.3.7
986 verbose cwd /root/nodebb
987 error Linux 3.10.23-xxxx-std-ipv6-64-vps
988 error argv "/usr/bin/node" "/usr/bin/npm" "rebuild"
989 error node v0.12.7
990 error npm  v2.11.3
991 error code ELIFECYCLE
992 error heapdump@0.3.7 install: `node-gyp rebuild`
992 error Exit status 1
993 error Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
993 error This is most likely a problem with the heapdump package,
993 error not with npm itself.
993 error Tell the author that this fails on your system:
993 error     node-gyp rebuild
993 error You can get their info via:
993 error     npm owner ls heapdump
993 error There is likely additional logging output above.
994 verbose exit [ 1, true ]
```

**Comment by julianlam** [comment]
Hm, quite weird. Again, this is suggesting that npm can't build its necessary dependencies, but is ultimately unrelated to NodeBB (I believe)...

Can you make sure `build-essential` is installed on your system, move `node_modules` out of the way, and then `npm i`?

Maybe `npm cache clear` before `npm i`, just to be safe.

**Comment by mrgame64** [comment]
`build-essential` was already installed and updated.

I've run these commands:
`
#Inside the nodebb folder
rm node_modules
npm cache clear
npm i
`

And after running `./nodebb upgrade`, I got this:
```
1. Bringing base dependencies up to date
2. Updating NodeBB data store schema
18/8 21:55 [13547] - error: Unable to initialize Redis! Is Redis installed? Error :Cannot find module 'redis'
3. Storing upgrade date in "package.json"

                                                                                                           NodeBB Upgrade Complete!
```

And I'm pretty sure my `redis-server` is up and running (confirmed via `redis-cli`)

**Comment by mrgame64** [comment]
After attempting to install `redis` manually via `npm install redis`, it looks like the `package.json` is missing `connect-redis` as well.

**Comment by julianlam** [comment]
Yup, this is okay, they are normally installed when you run `./nodebb
setup`.

**Comment by mrgame64** [comment]
So I'll just install them manually.

Shouldn't they be included in the `package.json`, though?

**Comment by julianlam** [comment]
@mrgame64 No, because some users are on Mongo, so we install the needed packages during setup. Technically on an upgrade, you shouldn't *have* to wipe `node_modules/`, so that's an issue in and of itself.

**Comment by mrgame64** [comment]
So in the end it was an NPM issue?

**Comment by julianlam** [comment]
Possibly... investigating it now. It actually seems to be an issue with `./nodebb upgrade`'s invocation of `npm install`.

**Comment by mrgame64** [comment]
I can add that when I ran `./nodebb upgrade` yesterday (still on the 0.7.2 release), it ran just fine

**Comment by julianlam** [comment]
... which is even weirder. Having it *sometimes* work isn't acceptable! :smile:

**Comment by julianlam** [comment]
Possibly small comfort for you @mrgame64, but `./nodebb upgrade` should work better (and not obliterate random packages) now.

... but since you have it working fine now, I suppose you're done here :smile: Thanks for helping me out!

**Comment by mrgame64** [comment]
No worries, glad I could help out :)
(and that I got my own problem solved BTW ^^ )
